### ISSUE TITLE
creating info table based on extracted tweets

### ISSUE THREAD

**Issue by behnazeslami** [chop-dbhi/twitter-adr-blstm#1]
@acocos @sgithens @jeffmax @bruth @penningtonj @murphyke Hi,

I have a question? in this link https://github.com/chop-dbhi/twitter-adr-blstm/blob/master/data/chop_adhd_adr_supp/train_tweet_annotations.tsv
How you can create that info table based on extracted tweets?

Please guide me more

Thank you so much

/Behnaz

**Comment by acocos** [comment]
Hi Behnaz, 

This annotation needs to be done manually (or via crowdsourcing). We used the tweet annotation guidelines published along with this paper:

Rachel Ginn, Pranoti Pimpalkhute, Azadeh Nikfarjam, Apurv Patki, Karen O'Connor, Abeed Sarker, Karen Smith and Graciela Gonzalez. Mining Twitter for Adverse Drug Reaction Mentions: A Corpus and Classification Benchmark. In proceedings of the Fourth Workshop on Building and Evaluating Resources for Health and Biomedical Text Processing (BioTxtM2014). May, 2014. Reykjavik, Iceland.
